import {
  Branch,
  CashRegister,
  Product,
  Customer,
  Supplier,
  SaleOrder,
  PurchaseOrder,
  GoodsReceivedNote,
  StockTransfer,
  StockAdjustment,
  DeliveryFleet,
  DeliveryType,
  WarehouseBin,
  WarrantyClaim,
  AccountLedger,
  AccountingVoucher,
  PromotionRule,
  DynamicPricingRule,
  Employee,
  AuditLog,
  UserProfile,
} from "./types";

export const INITIAL_BRANCHES: Branch[] = [
  {
    id: "BR-YGN-01",
    code: "YGN-HQ",
    name: "Yangon HQ Flagship & Experience Center",
    nameMy: "ရန်ကုန် HQ ပင်မဆိုင်ကြီး",
    city: "Yangon",
    address: "Pyay Road, Kamayut Township, Yangon",
    phone: "+95 9 790 123456",
    manager: "U Kyaw Zayar",
    registersCount: 3,
    status: "ACTIVE",
    monthlyTarget: 120000000,
    currentSales: 110500000,
    cashFloat: 1500000,
    warehouseCapacity: 8500,
    isHQ: true,
  },
  {
    id: "BR-MDY-01",
    code: "MDY-01",
    name: "Mandalay Mega Tech Hub",
    nameMy: "မန္တလေး မဟာနည်းပညာစင်တာ",
    city: "Mandalay",
    address: "78th Street, Between 30th & 31st, Chanayethazan, Mandalay",
    phone: "+95 9 790 654321",
    manager: "Daw Thandar Win",
    registersCount: 2,
    status: "ACTIVE",
    monthlyTarget: 80000000,
    currentSales: 78200000,
    cashFloat: 1000000,
    warehouseCapacity: 5200,
    isHQ: false,
  },
  {
    id: "BR-NPT-01",
    code: "NPT-01",
    name: "Naypyidaw Capital Smart Outlet",
    nameMy: "နေပြည်တော် စမတ်စတိုး",
    city: "Naypyidaw",
    address: "Junction Centre, Ottarathiri Township, Naypyidaw",
    phone: "+95 9 790 987654",
    manager: "U Aung Myo Tun",
    registersCount: 2,
    status: "ACTIVE",
    monthlyTarget: 45000000,
    currentSales: 39400000,
    cashFloat: 800000,
    warehouseCapacity: 3400,
    isHQ: false,
  },
  {
    id: "BR-WH-01",
    code: "CENTRAL-WH-YGN",
    name: "Yangon Central Logistics & Fulfillment Hub",
    nameMy: "ရန်ကုန် ဗဟိုထောက်ပံ့ရေးနှင့် အွန်လိုင်းဂိုဒေါင်ကြီး",
    city: "Yangon",
    address: "Hlaing Tharyar Industrial Zone 2, Yangon",
    phone: "+95 9 790 112233",
    manager: "Ko Min Thu",
    registersCount: 1,
    status: "ACTIVE",
    monthlyTarget: 25000000,
    currentSales: 17700000,
    cashFloat: 500000,
    warehouseCapacity: 28000,
    isHQ: false,
  },
  {
    id: "BR-WH-MDY-01",
    code: "REGIONAL-WH-MDY",
    name: "Mandalay Upper Myanmar Regional Depot",
    nameMy: "မန္တလေး အထက်မြန်မာပြည် ဗဟိုသိုလှောင်ရုံ",
    city: "Mandalay",
    address: "Myotha Industrial Park, Mandalay",
    phone: "+95 9 790 445566",
    manager: "U Soe Naing",
    registersCount: 1,
    status: "ACTIVE",
    monthlyTarget: 20000000,
    currentSales: 14500000,
    cashFloat: 500000,
    warehouseCapacity: 18000,
    isHQ: false,
  },
];

export const INITIAL_REGISTERS: CashRegister[] = [
  {
    id: "REG-YGN-01",
    branchId: "BR-YGN-01",
    name: "Yangon POS Terminal 01 (Main Express)",
    status: "OPEN",
    currentCash: 1250000,
    openedAt: "2026-08-21T08:30:00Z",
    openedBy: "Aye Aye Myint",
    todayTransactions: 48,
  },
  {
    id: "REG-YGN-02",
    branchId: "BR-YGN-01",
    name: "Yangon POS Terminal 02 (VIP & Mobile Pay)",
    status: "OPEN",
    currentCash: 890000,
    openedAt: "2026-08-21T08:35:00Z",
    openedBy: "Zin Mar Lwin",
    todayTransactions: 36,
  },
  {
    id: "REG-MDY-01",
    branchId: "BR-MDY-01",
    name: "Mandalay POS Terminal 01",
    status: "OPEN",
    currentCash: 950000,
    openedAt: "2026-08-21T09:00:00Z",
    openedBy: "Htet Naing Oo",
    todayTransactions: 31,
  },
  {
    id: "REG-NPT-01",
    branchId: "BR-NPT-01",
    name: "Naypyidaw POS Terminal 01",
    status: "OPEN",
    currentCash: 620000,
    openedAt: "2026-08-21T09:15:00Z",
    openedBy: "Sandar Win",
    todayTransactions: 19,
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: "PROD-001",
    sku: "APL-IP15PM-256",
    barcode: "880912345601",
    name: "iPhone 15 Pro Max (256GB - Natural Titanium)",
    nameMy: "အိုင်ဖုန်း ၁၅ ပရိုမက်စ် (၂၅၆ဂျီဘီ)",
    category: "Smartphones",
    brand: "Apple",
    costPrice: 4250000,
    sellingPrice: 4850000,
    uom: "Pcs",
    basePrices: [
      { name: "Retail Walk-in (Standard)", price: 4850000 },
      { name: "Wholesale (Bulk 5+)", price: 4550000 },
      { name: "VIP Platinum Tier", price: 4600000 },
      { name: "Dealer / Sub-agent", price: 4480000 },
      { name: "Online / E-Commerce Promo", price: 4750000 },
    ],
    image: "https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=500&auto=format&fit=crop&q=60",
    hasIMEI: true,
    warrantyMonths: 12,
    reorderLevel: 5,
    safetyStock: 8,
    leadTimeDays: 7,
    supplierId: "SUP-001",
    binLocation: "Aisle A1, Shelf 04 (High Security Cage)",
    branchStock: {
      "BR-YGN-01": 14,
      "BR-MDY-01": 3, // Low stock trigger
      "BR-NPT-01": 6,
      "BR-WH-01": 25,
    },
    tags: ["flagship", "bestseller", "imei-tracked"],
    salesVelocity: 3.2,
    serials: [
      { serial: "359876123456781", branchId: "BR-YGN-01", branchName: "Yangon HQ Flagship", status: "AVAILABLE", expiryDate: "2027-12-31", lotNumber: "LOT-2026-08A", mfgDate: "2026-05-10" },
      { serial: "359876123456782", branchId: "BR-YGN-01", branchName: "Yangon HQ Flagship", status: "AVAILABLE", expiryDate: "2027-12-31", lotNumber: "LOT-2026-08A", mfgDate: "2026-05-10" },
      { serial: "359876123456783", branchId: "BR-MDY-01", branchName: "Mandalay Mega Tech Hub", status: "AVAILABLE", expiryDate: "2027-12-31", lotNumber: "LOT-2026-08A", mfgDate: "2026-05-10" },
      { serial: "359876123456784", branchId: "BR-WH-01", branchName: "Yangon Central Logistics", status: "AVAILABLE", expiryDate: "2028-03-31", lotNumber: "LOT-2026-09B", mfgDate: "2026-06-15" },
    ],
    batches: [
      { batchNumber: "LOT-2026-08A", expiryDate: "2027-12-31", mfgDate: "2026-05-10", quantity: 23, branchId: "BR-YGN-01", branchName: "Yangon HQ Flagship", notes: "First-party Apple seal batch" },
      { batchNumber: "LOT-2026-09B", expiryDate: "2028-03-31", mfgDate: "2026-06-15", quantity: 25, branchId: "BR-WH-01", branchName: "Yangon Central Logistics", notes: "Warehouse fresh container intake" },
    ],
    stockMatrix: {
      enabled: true,
      colors: ["Natural Titanium", "Black Titanium", "White Titanium", "Blue Titanium"],
      sizes: ["256GB", "512GB", "1TB"],
      matrix: {
        "Natural Titanium__256GB__BR-YGN-01": 6,
        "Black Titanium__256GB__BR-YGN-01": 4,
        "White Titanium__256GB__BR-YGN-01": 2,
        "Blue Titanium__256GB__BR-YGN-01": 2,
        "Natural Titanium__256GB__BR-MDY-01": 2,
        "Black Titanium__256GB__BR-MDY-01": 1,
        "Natural Titanium__256GB__BR-NPT-01": 3,
        "Black Titanium__256GB__BR-NPT-01": 3,
        "Natural Titanium__256GB__BR-WH-01": 12,
        "Black Titanium__256GB__BR-WH-01": 8,
        "White Titanium__256GB__BR-WH-01": 5,
      },
    },
  },
  {
    id: "PROD-002",
    sku: "SAM-S24U-512",
    barcode: "880912345602",
    name: "Samsung Galaxy S24 Ultra (512GB - Titanium Gray)",
    nameMy: "ဆမ်ဆောင်း S24 အာထရာ (၅၁၂ဂျီဘီ)",
    category: "Smartphones",
    brand: "Samsung",
    costPrice: 3900000,
    sellingPrice: 4450000,
    uom: "Pcs",
    basePrices: [
      { name: "Retail Walk-in (Standard)", price: 4450000 },
      { name: "Wholesale (Bulk 5+)", price: 4150000 },
      { name: "VIP Platinum Tier", price: 4200000 },
      { name: "Dealer / Sub-agent", price: 4080000 },
      { name: "Online / E-Commerce Promo", price: 4350000 },
    ],
    image: "https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=500&auto=format&fit=crop&q=60",
    hasIMEI: true,
    warrantyMonths: 12,
    reorderLevel: 4,
    safetyStock: 6,
    leadTimeDays: 5,
    supplierId: "SUP-001",
    binLocation: "Aisle A1, Shelf 05",
    branchStock: {
      "BR-YGN-01": 9,
      "BR-MDY-01": 8,
      "BR-NPT-01": 4,
      "BR-WH-01": 18,
    },
    tags: ["galaxy-ai", "flagship", "imei-tracked"],
    salesVelocity: 2.8,
    serials: [
      { serial: "351234567890121", branchId: "BR-YGN-01", branchName: "Yangon HQ Flagship", status: "AVAILABLE", expiryDate: "2027-11-30", lotNumber: "LOT-SAM-24A", mfgDate: "2026-04-20" },
      { serial: "351234567890122", branchId: "BR-MDY-01", branchName: "Mandalay Mega Tech Hub", status: "AVAILABLE", expiryDate: "2027-11-30", lotNumber: "LOT-SAM-24A", mfgDate: "2026-04-20" },
    ],
    batches: [
      { batchNumber: "LOT-SAM-24A", expiryDate: "2027-11-30", mfgDate: "2026-04-20", quantity: 21, branchId: "BR-YGN-01", notes: "Samsung Regional Authorized Import" },
    ],
    stockMatrix: {
      enabled: true,
      colors: ["Titanium Gray", "Titanium Black", "Titanium Violet", "Titanium Yellow"],
      sizes: ["256GB", "512GB", "1TB"],
      matrix: {
        "Titanium Gray__512GB__BR-YGN-01": 5,
        "Titanium Black__512GB__BR-YGN-01": 4,
        "Titanium Gray__512GB__BR-MDY-01": 5,
        "Titanium Black__512GB__BR-MDY-01": 3,
        "Titanium Gray__512GB__BR-NPT-01": 2,
        "Titanium Black__512GB__BR-NPT-01": 2,
        "Titanium Gray__512GB__BR-WH-01": 10,
        "Titanium Black__512GB__BR-WH-01": 8,
      },
    },
  },
  {
    id: "PROD-003",
    sku: "APL-MBP14-M3",
    barcode: "880912345603",
    name: "MacBook Pro 14-inch M3 Pro (18GB / 512GB)",
    nameMy: "မက်ဘွတ်ပရို ၁၄ လက်မ M3 Pro",
    category: "Laptops & Computing",
    brand: "Apple",
    costPrice: 5800000,
    sellingPrice: 6500000,
    uom: "Pcs",
    basePrices: [
      { name: "Retail Walk-in (Standard)", price: 6500000 },
      { name: "Wholesale (Bulk 5+)", price: 6100000 },
      { name: "VIP Platinum Tier", price: 6250000 },
      { name: "Dealer / Sub-agent", price: 6050000 },
      { name: "Corporate / B2B Rate", price: 6180000 },
    ],
    image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=500&auto=format&fit=crop&q=60",
    hasIMEI: true,
    warrantyMonths: 24,
    reorderLevel: 3,
    safetyStock: 4,
    leadTimeDays: 10,
    supplierId: "SUP-002",
    binLocation: "Aisle B2, Shelf 01",
    branchStock: {
      "BR-YGN-01": 7,
      "BR-MDY-01": 4,
      "BR-NPT-01": 2, // Low stock
      "BR-WH-01": 12,
    },
    tags: ["workstation", "creative-pro", "high-ticket"],
    salesVelocity: 1.1,
    serials: [
      { serial: "C02XYZ123456", branchId: "BR-YGN-01", status: "AVAILABLE", expiryDate: "2028-10-31", lotNumber: "LOT-MBP-03" },
      { serial: "C02XYZ123457", branchId: "BR-MDY-01", status: "AVAILABLE", expiryDate: "2028-10-31", lotNumber: "LOT-MBP-03" },
    ],
    stockMatrix: {
      enabled: true,
      colors: ["Space Black", "Silver"],
      sizes: ["512GB SSD", "1TB SSD"],
      matrix: {
        "Space Black__512GB SSD__BR-YGN-01": 4,
        "Silver__512GB SSD__BR-YGN-01": 3,
        "Space Black__512GB SSD__BR-MDY-01": 2,
        "Silver__512GB SSD__BR-MDY-01": 2,
        "Space Black__512GB SSD__BR-NPT-01": 1,
        "Silver__512GB SSD__BR-NPT-01": 1,
        "Space Black__512GB SSD__BR-WH-01": 7,
        "Silver__512GB SSD__BR-WH-01": 5,
      },
    },
  },
  {
    id: "PROD-004",
    sku: "SNY-WH1000XM5",
    barcode: "880912345604",
    name: "Sony WH-1000XM5 Wireless Noise Canceling Headphones",
    nameMy: "ဆိုနီ ဆူညံသံဖျောက်ပရီမီယံ နားကြပ်",
    category: "Audio & Accessories",
    brand: "Sony",
    costPrice: 950000,
    sellingPrice: 1250000,
    uom: "Pcs",
    basePrices: [
      { name: "Retail Walk-in (Standard)", price: 1250000 },
      { name: "Wholesale (Bulk 10+)", price: 1100000 },
      { name: "VIP Platinum Tier", price: 1150000 },
      { name: "Dealer / Sub-agent", price: 1080000 },
      { name: "Online / E-Commerce Promo", price: 1190000 },
    ],
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500&auto=format&fit=crop&q=60",
    hasIMEI: true,
    warrantyMonths: 12,
    reorderLevel: 6,
    safetyStock: 10,
    leadTimeDays: 4,
    supplierId: "SUP-003",
    binLocation: "Aisle C1, Bin 12",
    branchStock: {
      "BR-YGN-01": 15,
      "BR-MDY-01": 11,
      "BR-NPT-01": 1, // Critical low
      "BR-WH-01": 32,
    },
    tags: ["audio", "anc", "high-margin"],
    salesVelocity: 4.5,
    serials: [
      { serial: "SNY-XM5-998811", branchId: "BR-YGN-01", status: "AVAILABLE", expiryDate: "2028-06-30", lotNumber: "LOT-SNY-01" },
    ],
    stockMatrix: {
      enabled: true,
      colors: ["Black", "Silver", "Midnight Blue"],
      sizes: ["Standard"],
      matrix: {
        "Black__Standard__BR-YGN-01": 8,
        "Silver__Standard__BR-YGN-01": 4,
        "Midnight Blue__Standard__BR-YGN-01": 3,
        "Black__Standard__BR-MDY-01": 6,
        "Silver__Standard__BR-MDY-01": 5,
        "Black__Standard__BR-NPT-01": 1,
        "Black__Standard__BR-WH-01": 16,
        "Silver__Standard__BR-WH-01": 10,
        "Midnight Blue__Standard__BR-WH-01": 6,
      },
    },
  },
  {
    id: "PROD-005",
    sku: "APL-AW-U2",
    barcode: "880912345605",
    name: "Apple Watch Ultra 2 (GPS + Cellular, Titanium)",
    nameMy: "အက်ပဲလ်ဝေါ့ချ် အာထရာ ၂ စမတ်နာရီ",
    category: "Wearables",
    brand: "Apple",
    costPrice: 2400000,
    sellingPrice: 2850000,
    uom: "Pcs",
    basePrices: [
      { name: "Retail Walk-in (Standard)", price: 2850000 },
      { name: "Wholesale (Bulk 5+)", price: 2600000 },
      { name: "VIP Platinum Tier", price: 2680000 },
      { name: "Dealer / Sub-agent", price: 2550000 },
      { name: "Online / E-Commerce Promo", price: 2750000 },
    ],
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500&auto=format&fit=crop&q=60",
    hasIMEI: true,
    warrantyMonths: 12,
    reorderLevel: 4,
    safetyStock: 5,
    leadTimeDays: 6,
    supplierId: "SUP-001",
    binLocation: "Aisle C2, Shelf 08",
    branchStock: {
      "BR-YGN-01": 8,
      "BR-MDY-01": 6,
      "BR-NPT-01": 5,
      "BR-WH-01": 14,
    },
    tags: ["wearables", "fitness"],
    salesVelocity: 2.1,
  },
  {
    id: "PROD-006",
    sku: "ANK-65W-GAN",
    barcode: "880912345606",
    name: "Anker Prime 65W GaN Fast Charger 3-Port",
    nameMy: "အန်ကာ ၆၅ ဝပ် အားသွင်းခေါင်းအမြန်",
    category: "Audio & Accessories",
    brand: "Anker",
    costPrice: 120000,
    sellingPrice: 185000,
    uom: "Box",
    basePrices: [
      { name: "Retail Walk-in (Standard)", price: 185000 },
      { name: "Wholesale (Box of 10)", price: 155000 },
      { name: "VIP Platinum Tier", price: 165000 },
      { name: "Dealer / Sub-agent", price: 145000 },
      { name: "Online / E-Commerce Promo", price: 175000 },
    ],
    image: "https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=500&auto=format&fit=crop&q=60",
    hasIMEI: false,
    warrantyMonths: 18,
    reorderLevel: 15,
    safetyStock: 25,
    leadTimeDays: 3,
    supplierId: "SUP-003",
    binLocation: "Aisle D3, Shelf 02",
    branchStock: {
      "BR-YGN-01": 45,
      "BR-MDY-01": 38,
      "BR-NPT-01": 22,
      "BR-WH-01": 110,
    },
    tags: ["charger", "fast-moving", "accessory"],
    salesVelocity: 12.0,
    batches: [
      { batchNumber: "LOT-ANK-2026", expiryDate: "2029-12-31", mfgDate: "2026-01-15", quantity: 215, branchId: "BR-WH-01", notes: "GaN III High Efficiency Batch" },
    ],
  },
  {
    id: "PROD-007",
    sku: "LOGI-MXM3S",
    barcode: "880912345607",
    name: "Logitech MX Master 3S Wireless Performance Mouse",
    nameMy: "လော့ဂျီတက်ခ် MX Master 3S ပရော်ဖက်ရှင်နယ် မောက်စ်",
    category: "Laptops & Computing",
    brand: "Logitech",
    costPrice: 280000,
    sellingPrice: 385000,
    uom: "Pcs",
    basePrices: [
      { name: "Retail Walk-in (Standard)", price: 385000 },
      { name: "Wholesale (Carton 10+)", price: 330000 },
      { name: "VIP Platinum Tier", price: 350000 },
      { name: "Dealer / Sub-agent", price: 320000 },
      { name: "Online / E-Commerce Promo", price: 365000 },
    ],
    image: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=500&auto=format&fit=crop&q=60",
    hasIMEI: false,
    warrantyMonths: 12,
    reorderLevel: 8,
    safetyStock: 12,
    leadTimeDays: 4,
    supplierId: "SUP-002",
    binLocation: "Aisle D1, Shelf 06",
    branchStock: {
      "BR-YGN-01": 21,
      "BR-MDY-01": 14,
      "BR-NPT-01": 9,
      "BR-WH-01": 50,
    },
    tags: ["productivity", "bestseller"],
    salesVelocity: 5.4,
    stockMatrix: {
      enabled: true,
      colors: ["Graphite", "Pale Gray"],
      sizes: ["Standard"],
      matrix: {
        "Graphite__Standard__BR-YGN-01": 14,
        "Pale Gray__Standard__BR-YGN-01": 7,
        "Graphite__Standard__BR-MDY-01": 9,
        "Pale Gray__Standard__BR-MDY-01": 5,
        "Graphite__Standard__BR-NPT-01": 6,
        "Pale Gray__Standard__BR-NPT-01": 3,
        "Graphite__Standard__BR-WH-01": 32,
        "Pale Gray__Standard__BR-WH-01": 18,
      },
    },
  },
  {
    id: "PROD-008",
    sku: "DYS-V15-DET",
    barcode: "880912345608",
    name: "Dyson V15 Detect Cordless Smart Vacuum",
    nameMy: "ဒိုင်ဆင် V15 စမတ်ကြိုးမဲ့ဖုန်စုပ်စက်",
    category: "Smart Home",
    brand: "Dyson",
    costPrice: 2200000,
    sellingPrice: 2750000,
    uom: "Set",
    basePrices: [
      { name: "Retail Walk-in (Standard)", price: 2750000 },
      { name: "Wholesale (Bulk 3+)", price: 2450000 },
      { name: "VIP Platinum Tier", price: 2550000 },
      { name: "Dealer / Sub-agent", price: 2400000 },
      { name: "Online / E-Commerce Promo", price: 2650000 },
    ],
    image: "https://images.unsplash.com/photo-1558317374-067fb5f30001?w=500&auto=format&fit=crop&q=60",
    hasIMEI: true,
    warrantyMonths: 24,
    reorderLevel: 2,
    safetyStock: 3,
    leadTimeDays: 8,
    supplierId: "SUP-004",
    binLocation: "Aisle E1, Pallet 03",
    branchStock: {
      "BR-YGN-01": 5,
      "BR-MDY-01": 3,
      "BR-NPT-01": 2,
      "BR-WH-01": 9,
    },
    tags: ["smart-home", "lifestyle"],
    salesVelocity: 0.9,
    serials: [
      { serial: "DYS-V15-8831001", branchId: "BR-YGN-01", status: "AVAILABLE", expiryDate: "2029-12-31", lotNumber: "LOT-DYS-01" },
    ],
  },
];

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: "CUST-001",
    name: "U Thant Zin",
    phone: "09450011223",
    email: "thantzin.tech@gmail.com",
    membershipTier: "PLATINUM",
    loyaltyPoints: 4850,
    totalSpend: 34500000,
    outstandingBalance: 0,
    creditLimit: 5000000,
    joinedDate: "2024-03-15",
    lastVisit: "2026-08-19",
    city: "Yangon",
  },
  {
    id: "CUST-002",
    name: "Daw May Thu Khaing",
    phone: "09798877665",
    email: "maythukhaing@hotmail.com",
    membershipTier: "GOLD",
    loyaltyPoints: 2100,
    totalSpend: 16800000,
    outstandingBalance: 450000,
    creditLimit: 3000000,
    joinedDate: "2024-08-20",
    lastVisit: "2026-08-20",
    city: "Mandalay",
  },
  {
    id: "CUST-003",
    name: "Ko Min Htet San",
    phone: "09971234889",
    email: "minhtet.san@gmail.com",
    membershipTier: "SILVER",
    loyaltyPoints: 750,
    totalSpend: 6200000,
    outstandingBalance: 0,
    creditLimit: 1500000,
    joinedDate: "2025-01-10",
    lastVisit: "2026-08-18",
    city: "Yangon",
  },
  {
    id: "CUST-004",
    name: "Apex Engineering Corp (B2B)",
    phone: "09254332211",
    email: "procurement@apexmyanmar.com",
    membershipTier: "PLATINUM",
    loyaltyPoints: 12400,
    totalSpend: 92000000,
    outstandingBalance: 12500000,
    creditLimit: 25000000,
    joinedDate: "2023-11-01",
    lastVisit: "2026-08-15",
    city: "Naypyidaw",
  },
];

export const INITIAL_SUPPLIERS: Supplier[] = [
  {
    id: "SUP-001",
    name: "Apex Tech Distribution APAC",
    code: "APEX-SG",
    contactPerson: "Marcus Vance",
    phone: "+65 6789 0123",
    email: "orders@apextech.com.sg",
    category: "Apple & Samsung Authorized",
    paymentTerms: "Net 30 Days",
    onTimeDeliveryRate: 98.2,
    rating: 4.9,
    outstandingPayable: 45000000,
    leadTimeAvgDays: 6,
    country: "Singapore",
  },
  {
    id: "SUP-002",
    name: "Silicon Hub Logistics Co., Ltd.",
    code: "SILICON-MM",
    contactPerson: "U Tun Lin",
    phone: "+95 9 4200 9988",
    email: "procure@siliconhub.com.mm",
    category: "Laptops & Computing Components",
    paymentTerms: "Net 15 Days",
    onTimeDeliveryRate: 94.5,
    rating: 4.6,
    outstandingPayable: 22800000,
    leadTimeAvgDays: 8,
    country: "Myanmar",
  },
  {
    id: "SUP-003",
    name: "Anker & Audio Global Direct",
    code: "ANKER-CN",
    contactPerson: "Ms. Lin Chen",
    phone: "+86 755 8899 0011",
    email: "b2b@ankerglobal.cn",
    category: "Audio, Power & Smart Accessories",
    paymentTerms: "Letter of Credit (LC)",
    onTimeDeliveryRate: 96.8,
    rating: 4.8,
    outstandingPayable: 14200000,
    leadTimeAvgDays: 5,
    country: "China",
  },
  {
    id: "SUP-004",
    name: "Lifestyle Smart Innovations Co.",
    code: "LIFESTYLE-TH",
    contactPerson: "Somchai Prasert",
    phone: "+66 2 345 6789",
    email: "somchai@smartlifestyle.co.th",
    category: "Smart Appliances & Robotic Tech",
    paymentTerms: "Net 45 Days",
    onTimeDeliveryRate: 92.0,
    rating: 4.4,
    outstandingPayable: 9500000,
    leadTimeAvgDays: 10,
    country: "Thailand",
  },
];

export const INITIAL_ORDERS: SaleOrder[] = [
  {
    id: "ORD-20260821-001",
    orderNumber: "INV-260821-001",
    branchId: "BR-YGN-01",
    branchName: "Yangon HQ Flagship",
    registerId: "REG-YGN-01",
    cashierId: "EMP-003",
    cashierName: "Aye Aye Myint",
    customerId: "CUST-001",
    customerName: "U Thant Zin",
    customerPhone: "09450011223",
    items: [
      {
        product: INITIAL_PRODUCTS[0], // iPhone 15 Pro Max
        quantity: 1,
        unitPrice: 4850000,
        discount: 100000,
        discountType: "FIXED",
        imeiList: ["358923114567890"],
      },
      {
        product: INITIAL_PRODUCTS[5], // Anker 65W
        quantity: 2,
        unitPrice: 185000,
        discount: 0,
        discountType: "FIXED",
      },
    ],
    subtotal: 5220000,
    discountAmount: 100000,
    taxAmount: 256000,
    grandTotal: 5376000,
    payments: [
      { method: "KBZPAY", amount: 4000000, referenceNumber: "KP-99882211" },
      { method: "CASH", amount: 1376000 },
    ],
    changeGiven: 0,
    status: "COMPLETED",
    createdAt: "2026-08-21T09:45:00Z",
    imeiSold: {
      "PROD-001": ["358923114567890"],
    },
  },
  {
    id: "ORD-20260821-002",
    orderNumber: "INV-260821-002",
    branchId: "BR-MDY-01",
    branchName: "Mandalay Mega Tech Hub",
    registerId: "REG-MDY-01",
    cashierId: "EMP-005",
    cashierName: "Htet Naing Oo",
    customerId: "CUST-002",
    customerName: "Daw May Thu Khaing",
    customerPhone: "09798877665",
    items: [
      {
        product: INITIAL_PRODUCTS[3], // Sony XM5
        quantity: 1,
        unitPrice: 1250000,
        discount: 5,
        discountType: "PERCENT",
        imeiList: ["SN-SONY-990812"],
      },
    ],
    subtotal: 1250000,
    discountAmount: 62500,
    taxAmount: 59375,
    grandTotal: 1246875,
    payments: [{ method: "WAVEPAY", amount: 1246875, referenceNumber: "WV-88776622" }],
    changeGiven: 0,
    status: "COMPLETED",
    createdAt: "2026-08-21T10:15:00Z",
  },
];

export const INITIAL_PURCHASE_ORDERS: PurchaseOrder[] = [
  {
    id: "PO-2026-088",
    poNumber: "PO-2608-088",
    supplierId: "SUP-001",
    supplierName: "Apex Tech Distribution APAC",
    destinationBranchId: "BR-WH-01",
    destinationBranchName: "Central Logistics Warehouse",
    items: [
      {
        productId: "PROD-001",
        productName: "iPhone 15 Pro Max (256GB)",
        sku: "APL-IP15PM-256",
        quantity: 30,
        unitCost: 4250000,
        totalCost: 127500000,
        receivedQty: 30,
      },
      {
        productId: "PROD-002",
        productName: "Samsung Galaxy S24 Ultra (512GB)",
        sku: "SAM-S24U-512",
        quantity: 20,
        unitCost: 3900000,
        totalCost: 78000000,
        receivedQty: 20,
      },
    ],
    totalAmount: 205500000,
    status: "GRN_COMPLETED",
    paymentTerms: "Net 30 Days",
    expectedDate: "2026-08-18",
    createdAt: "2026-08-10T04:00:00Z",
    grnNumber: "GRN-2608-042",
    threeWayMatched: true,
  },
  {
    id: "PO-2026-089",
    poNumber: "PO-2608-089",
    supplierId: "SUP-003",
    supplierName: "Anker & Audio Global Direct",
    destinationBranchId: "BR-WH-01",
    destinationBranchName: "Central Logistics Warehouse",
    items: [
      {
        productId: "PROD-004",
        productName: "Sony WH-1000XM5 ANC Headphones",
        sku: "SNY-WH1000XM5",
        quantity: 40,
        unitCost: 950000,
        totalCost: 38000000,
        receivedQty: 0,
      },
      {
        productId: "PROD-006",
        productName: "Anker 65W GaN Charger",
        sku: "ANK-65W-GAN",
        quantity: 150,
        unitCost: 120000,
        totalCost: 18000000,
        receivedQty: 0,
      },
    ],
    totalAmount: 56000000,
    status: "DISPATCHED",
    paymentTerms: "Letter of Credit",
    expectedDate: "2026-08-24",
    createdAt: "2026-08-16T08:00:00Z",
  },
];

export const INITIAL_GRN: GoodsReceivedNote[] = [
  {
    id: "GRN-2608-042",
    grnNumber: "GRN-2608-042",
    poNumber: "PO-2608-088",
    supplierName: "Apex Tech Distribution APAC",
    branchId: "BR-WH-01",
    branchName: "Central Logistics Warehouse",
    receivedDate: "2026-08-18T14:30:00Z",
    receivedBy: "Ko Min Thu (Warehouse Lead)",
    items: [
      {
        productId: "PROD-001",
        productName: "iPhone 15 Pro Max (256GB)",
        expectedQty: 30,
        acceptedQty: 30,
        rejectedQty: 0,
        assignedIMEIs: ["358923114567890", "358923114567891", "358923114567892"],
      },
      {
        productId: "PROD-002",
        productName: "Samsung Galaxy S24 Ultra (512GB)",
        expectedQty: 20,
        acceptedQty: 20,
        rejectedQty: 0,
      },
    ],
    inspectionStatus: "PASSED",
    remarks: "Full container sealed and verified against packing slip. No physical box damages.",
  },
];

export const INITIAL_STOCK_TRANSFERS: StockTransfer[] = [
  {
    id: "TRF-2608-019",
    transferNumber: "TRF-2608-019",
    fromBranchId: "BR-WH-01",
    fromBranchName: "Central Logistics Warehouse",
    toBranchId: "BR-MDY-01",
    toBranchName: "Mandalay Mega Tech Hub",
    items: [
      {
        productId: "PROD-001",
        productName: "iPhone 15 Pro Max (256GB)",
        sku: "APL-IP15PM-256",
        quantity: 10,
      },
      {
        productId: "PROD-004",
        productName: "Sony WH-1000XM5 Headphones",
        sku: "SNY-WH1000XM5",
        quantity: 8,
      },
    ],
    requestedBy: "Daw Thandar Win (MDY Manager)",
    dispatchedAt: "2026-08-20T11:00:00Z",
    receivedAt: "2026-08-20T17:00:00Z",
    driverName: "U Aung Gyi",
    vehicleNumber: "YGN 4K-9921 (Fleet Van 02)",
    status: "RECEIVED",
    notes: "Urgent replenishment for MDY tech festival promotion weekend completed.",
  },
  {
    id: "TRF-2608-018",
    transferNumber: "TRF-2608-018",
    fromBranchId: "BR-WH-01",
    fromBranchName: "Central Logistics Warehouse",
    toBranchId: "BR-YGN-01",
    toBranchName: "Yangon HQ Flagship",
    items: [
      {
        productId: "PROD-006",
        productName: "Anker 65W GaN Charger",
        sku: "ANK-65W-GAN",
        quantity: 30,
      },
    ],
    requestedBy: "U Kyaw Zayar",
    dispatchedAt: "2026-08-19T09:00:00Z",
    receivedAt: "2026-08-19T13:45:00Z",
    status: "RECEIVED",
    notes: "Standard weekly stock rebalance completed.",
  },
];

export const INITIAL_STOCK_ADJUSTMENTS: StockAdjustment[] = [
  {
    id: "ADJ-2608-005",
    adjustmentNumber: "ADJ-2608-005",
    branchId: "BR-YGN-01",
    branchName: "Yangon HQ Flagship",
    productId: "PROD-006",
    productName: "Anker 65W GaN Fast Charger",
    sku: "ANK-65W-GAN",
    previousStock: 46,
    adjustedStock: 45,
    difference: -1,
    reason: "DAMAGED",
    adjustedBy: "Aye Aye Myint",
    date: "2026-08-20T16:00:00Z",
    approvedBy: "U Kyaw Zayar (Branch Manager)",
  },
];

export const INITIAL_DELIVERY_TYPES: DeliveryType[] = [
  {
    id: "DT-SAME-DAY-BIKE",
    code: "EXP-CITY-BIKE",
    name: "Express Same-Day City Bike Courier",
    nameMy: "မြို့တွင်း အမြန် ဆိုင်ကယ် အရောက်ပို့",
    vehicleCategory: "MOTORBIKE",
    estimatedSLA: "2-4 Hours (Same Day)",
    baseRate: 2500,
    ratePerKm: 300,
    maxWeightKg: 15,
    maxVolumeCbm: 0.1,
    activeVehiclesCount: 8,
    status: "ACTIVE",
    description: "Fast intracity delivery for mobile phones, accessories, and small parcels.",
  },
  {
    id: "DT-LIGHT-VAN",
    code: "URBAN-VAN-1T",
    name: "Urban 1-Ton Electric / Light Cargo Van",
    nameMy: "မြို့တွင်း ၁ တန် အလတ်စား ကုန်တင်ယာဉ်",
    vehicleCategory: "LIGHT_VAN",
    estimatedSLA: "Same Day / Next Morning",
    baseRate: 12000,
    ratePerKm: 600,
    maxWeightKg: 1000,
    maxVolumeCbm: 4.5,
    activeVehiclesCount: 5,
    status: "ACTIVE",
    description: "Ideal for bulk electronics boxes, display TVs, multiple retail order drops.",
  },
  {
    id: "DT-HIGHWAY-6W",
    code: "HWY-6W-INTERCITY",
    name: "Yangon-Mandalay Highway 6-Wheeler Trunk Truck",
    nameMy: "ရန်ကုန်-မန္တလေး အဝေးပြေး ၆ ဘီး ကုန်တင်ယာဉ်ကြီး",
    vehicleCategory: "SIX_WHEELER",
    estimatedSLA: "24 Hours (Highway Express)",
    baseRate: 85000,
    ratePerKm: 1200,
    maxWeightKg: 8000,
    maxVolumeCbm: 28,
    activeVehiclesCount: 3,
    status: "ACTIVE",
    description: "Scheduled daily linehaul between Yangon Central Hub, Naypyidaw, and Mandalay Regional Depot.",
  },
  {
    id: "DT-COLD-REEFER",
    code: "COLD-CHAIN-REEFER",
    name: "Temperature-Controlled Cold-Chain Reefer Van",
    nameMy: "အအေးခန်း ကုန်တင်ယာဉ်ငယ်",
    vehicleCategory: "COLD_CHAIN_REEFER",
    estimatedSLA: "24-48 Hours Insulated",
    baseRate: 65000,
    ratePerKm: 950,
    maxWeightKg: 2500,
    maxVolumeCbm: 12,
    activeVehiclesCount: 2,
    status: "ACTIVE",
    description: "Specialized climate-controlled transit for delicate batteries, sensors, and premium sealed optics.",
  },
  {
    id: "DT-HEAVY-12W",
    code: "HEAVY-12W-CONTAINER",
    name: "Heavy 12-Wheeler Container Carrier",
    nameMy: "၁၂ ဘီး ကွန်တိန်နာ တင်တွဲကားကြီး",
    vehicleCategory: "TWELVE_WHEELER",
    estimatedSLA: "36-48 Hours",
    baseRate: 250000,
    ratePerKm: 2000,
    maxWeightKg: 24000,
    maxVolumeCbm: 65,
    activeVehiclesCount: 2,
    status: "ACTIVE",
    description: "Port-to-Warehouse direct container freight and mega bulk stock relocation.",
  },
];

export const INITIAL_WAREHOUSE_BINS: WarehouseBin[] = [
  {
    id: "BIN-YGN-A01-01",
    binCode: "BIN-YGN-A01-R1-S1",
    warehouseId: "BR-WH-01",
    warehouseName: "Yangon Central Logistics & Fulfillment Hub",
    warehouseCategory: "HIGH_VALUE_VAULT",
    zone: "Zone A (High-Value Secured Vault)",
    aisle: "Aisle A-01",
    rack: "Rack R-01",
    shelf: "Tier 1 (Eye-Level Secure)",
    maxCapacityUnits: 250,
    currentUnits: 230,
    occupancyPercentage: 92,
    designatedCategory: "Smartphones & Tablets (iPhone, iPad, Galaxy S)",
    barcode: "BIN-WH-YGN-A01-01",
    status: "NEAR_FULL",
    notes: "Requires biometric badge entry and dual-custody verification.",
  },
  {
    id: "BIN-YGN-B02-03",
    binCode: "BIN-YGN-B02-R3-S2",
    warehouseId: "BR-WH-01",
    warehouseName: "Yangon Central Logistics & Fulfillment Hub",
    warehouseCategory: "COMPUTING_DISPLAYS",
    zone: "Zone B (Computing & Large Displays)",
    aisle: "Aisle B-02",
    rack: "Rack R-03",
    shelf: "Tier 2 (Heavy Duty Reinforced)",
    maxCapacityUnits: 120,
    currentUnits: 78,
    occupancyPercentage: 65,
    designatedCategory: "MacBooks, Dell XPS, Gaming Monitors",
    barcode: "BIN-WH-YGN-B02-03",
    status: "AVAILABLE",
    notes: "Equipped with padded anti-shock rubber base liner.",
  },
  {
    id: "BIN-YGN-C01-04",
    binCode: "BIN-YGN-C01-R1-S4",
    warehouseId: "BR-WH-01",
    warehouseName: "Yangon Central Logistics & Fulfillment Hub",
    warehouseCategory: "FAST_MOVING_PICK",
    zone: "Zone C (Fast-Moving Pick-Face)",
    aisle: "Aisle C-01",
    rack: "Rack R-01",
    shelf: "Tier 4 (Gravity Flow Rack)",
    maxCapacityUnits: 500,
    currentUnits: 200,
    occupancyPercentage: 40,
    designatedCategory: "Audio, Earbuds, MagSafe Chargers, Cables",
    barcode: "BIN-WH-YGN-C01-04",
    status: "AVAILABLE",
    notes: "High throughput picking area near packing line.",
  },
  {
    id: "BIN-YGN-D01-01",
    binCode: "BIN-YGN-D01-STAGE-01",
    warehouseId: "BR-WH-01",
    warehouseName: "Yangon Central Logistics & Fulfillment Hub",
    warehouseCategory: "DISPATCH_STAGING",
    zone: "Zone D (Dispatch & Cross-Docking Staging)",
    aisle: "Dock 1-4",
    rack: "Bay D-01",
    shelf: "Floor Staging Pallet Slots",
    maxCapacityUnits: 600,
    currentUnits: 480,
    occupancyPercentage: 80,
    designatedCategory: "Pending Inter-Branch Manifests & Outbound Couriers",
    barcode: "BIN-WH-YGN-D01-01",
    status: "AVAILABLE",
    notes: "Rapid transit zone. Cleared daily onto Highway Fleet.",
  },
  {
    id: "BIN-MDY-A01-01",
    binCode: "BIN-MDY-A01-R1-S1",
    warehouseId: "BR-WH-MDY-01",
    warehouseName: "Mandalay Upper Myanmar Regional Depot",
    warehouseCategory: "HIGH_VALUE_VAULT",
    zone: "Zone A (Upper Myanmar High-Value Vault)",
    aisle: "Aisle M-01",
    rack: "Rack R-01",
    shelf: "Tier 1 (Secure Vault)",
    maxCapacityUnits: 180,
    currentUnits: 110,
    occupancyPercentage: 61,
    designatedCategory: "Flagship Mobile Devices & Laptops",
    barcode: "BIN-WH-MDY-A01-01",
    status: "AVAILABLE",
    notes: "Mandalay regional buffer stock for Upper Myanmar branches.",
  },
  {
    id: "BIN-MDY-B01-02",
    binCode: "BIN-MDY-B01-R2-S2",
    warehouseId: "BR-WH-MDY-01",
    warehouseName: "Mandalay Upper Myanmar Regional Depot",
    warehouseCategory: "BULK_PALLET",
    zone: "Zone B (Bulk Pallet Reserve)",
    aisle: "Aisle M-02",
    rack: "Rack R-02",
    shelf: "Tier 3 (Pallet Racking)",
    maxCapacityUnits: 400,
    currentUnits: 350,
    occupancyPercentage: 88,
    designatedCategory: "Monitors, Desktop Towers & Accessories",
    barcode: "BIN-WH-MDY-B01-02",
    status: "NEAR_FULL",
    notes: "Direct forklift accessible pallet slots.",
  },
];

export const INITIAL_DELIVERIES: DeliveryFleet[] = [
  {
    id: "DLV-9901",
    trackingNumber: "TRK-260821-YGN-01",
    orderId: "ORD-20260821-001",
    deliveryTypeId: "DT-SAME-DAY-BIKE",
    deliveryTypeName: "Express Same-Day City Bike Courier",
    warehouseId: "BR-WH-01",
    warehouseName: "Yangon Central Logistics & Fulfillment Hub",
    recipientName: "U Thant Zin",
    recipientPhone: "09450011223",
    deliveryAddress: "No. 44, Inya Road, Bahan Township, Yangon",
    driverName: "Ko Soe Moe",
    driverPhone: "09771122334",
    vehicle: "Honda Wave Express Bike 04",
    status: "OUT_FOR_DELIVERY",
    estimatedArrival: "Today, 02:30 PM",
  },
  {
    id: "DLV-9902",
    trackingNumber: "TRK-260820-MDY-09",
    transferId: "TRF-2608-019",
    deliveryTypeId: "DT-HIGHWAY-6W",
    deliveryTypeName: "Yangon-Mandalay Highway 6-Wheeler Trunk Truck",
    warehouseId: "BR-WH-01",
    warehouseName: "Yangon Central Logistics & Fulfillment Hub",
    recipientName: "Mandalay Hub Depot Receiver",
    recipientPhone: "09790654321",
    deliveryAddress: "78th St, Chanayethazan, Mandalay",
    driverName: "U Aung Gyi",
    driverPhone: "0922119988",
    vehicle: "Isuzu 3-Ton Fleet Truck (YGN 4K-9921)",
    status: "IN_TRANSIT",
    estimatedArrival: "Tomorrow, 09:00 AM",
  },
];

export const INITIAL_WARRANTY_CLAIMS: WarrantyClaim[] = [
  {
    id: "RMA-2608-012",
    ticketNumber: "RMA-2608-012",
    imeiOrSerial: "358923114567890",
    productName: "iPhone 15 Pro Max (256GB)",
    customerName: "U Thant Zin",
    customerPhone: "09450011223",
    saleDate: "2026-03-12",
    warrantyExpiryDate: "2027-03-12",
    issueDescription: "Screen flickering on top left bezel after dropping on wood surface.",
    technicianAssigned: "Mg Hlaing (Senior Apple Certified Tech)",
    status: "DIAGNOSING",
    costEstimate: 0, // Covered under AppleCare+ warranty
    dateOpened: "2026-08-20T10:00:00Z",
  },
  {
    id: "RMA-2608-011",
    ticketNumber: "RMA-2608-011",
    imeiOrSerial: "SN-SONY-990812",
    productName: "Sony WH-1000XM5 ANC",
    customerName: "Daw May Thu Khaing",
    customerPhone: "09798877665",
    saleDate: "2025-11-05",
    warrantyExpiryDate: "2026-11-05",
    issueDescription: "Right earcup touch sensor unresponsive.",
    technicianAssigned: "Ko Phyo (Audio Specialist)",
    status: "REPAIRED",
    costEstimate: 0,
    dateOpened: "2026-08-15T11:20:00Z",
    resolvedDate: "2026-08-19T15:00:00Z",
  },
];

export const INITIAL_ACCOUNTS: AccountLedger[] = [
  { id: "ACC-101", code: "1010", name: "Cash in Hand & Registers", category: "ASSET", balance: 14500000, normalBalance: "DEBIT" },
  { id: "ACC-102", code: "1020", name: "KBZPay & WavePay Merchant Clearing", category: "ASSET", balance: 68400000, normalBalance: "DEBIT" },
  { id: "ACC-103", code: "1030", name: "CB Bank / KBZ Bank Corporate Account", category: "ASSET", balance: 245000000, normalBalance: "DEBIT" },
  { id: "ACC-104", code: "1040", name: "Merchandise Inventory Asset", category: "ASSET", balance: 412000000, normalBalance: "DEBIT" },
  { id: "ACC-105", code: "1050", name: "Accounts Receivable (Customer Credit)", category: "ASSET", balance: 12950000, normalBalance: "DEBIT" },
  { id: "ACC-201", code: "2010", name: "Accounts Payable (Vendor Balances)", category: "LIABILITY", balance: 91500000, normalBalance: "CREDIT" },
  { id: "ACC-202", code: "2020", name: "Commercial Tax (5%) Payable to IRD", category: "LIABILITY", balance: 12290000, normalBalance: "CREDIT" },
  { id: "ACC-301", code: "3010", name: "Owners Equity & Paid-in Capital", category: "EQUITY", balance: 400000000, normalBalance: "CREDIT" },
  { id: "ACC-401", code: "4010", name: "Retail & Online Sales Revenue", category: "REVENUE", balance: 245800000, normalBalance: "CREDIT" },
  { id: "ACC-501", code: "5010", name: "Cost of Goods Sold (COGS)", category: "EXPENSE", balance: 184350000, normalBalance: "DEBIT" },
  { id: "ACC-502", code: "5020", name: "Store Operating & Staff Payroll Expense", category: "EXPENSE", balance: 21500000, normalBalance: "DEBIT" },
];

export const INITIAL_VOUCHERS: AccountingVoucher[] = [
  {
    id: "VCH-2608-091",
    voucherNumber: "CRV-2608-091",
    type: "CRV",
    date: "2026-08-21",
    branchId: "BR-YGN-01",
    branchName: "Yangon HQ Flagship",
    debitAccount: "1010 - Cash in Hand & Registers",
    creditAccount: "4010 - Retail Sales Revenue",
    amount: 1376000,
    narration: "Daily POS cash receipt collection from Register 01",
    approvedBy: "U Kyaw Zayar",
    referenceNo: "INV-260821-001",
  },
  {
    id: "VCH-2608-090",
    voucherNumber: "BPV-2608-090",
    type: "BPV",
    date: "2026-08-20",
    branchId: "BR-YGN-01",
    branchName: "Yangon HQ Flagship",
    debitAccount: "2010 - Accounts Payable",
    creditAccount: "1030 - CB Bank Corporate",
    amount: 35000000,
    narration: "Partial payment settlement to Apex Tech Distribution (PO-2608-088)",
    approvedBy: "Executive Board",
    referenceNo: "CHQ-889900",
  },
];

export const INITIAL_PROMOTIONS: PromotionRule[] = [
  {
    id: "PROMO-001",
    code: "WEEKEND10",
    title: "Weekend Flash Tech Sale 10% Off",
    type: "PERCENTAGE",
    discountValue: 10,
    minSpend: 500000,
    startDate: "2026-08-20",
    endDate: "2026-08-25",
    active: true,
    branchRestrictions: [],
    usageCount: 42,
    usageLimit: 200,
  },
  {
    id: "PROMO-002",
    code: "CASH50K",
    title: "50,000 MMK Cash Discount Voucher (ငွေသား ၅ သောင်း လျှော့ပေး)",
    type: "FIXED_AMOUNT",
    discountValue: 50000,
    minSpend: 800000,
    startDate: "2026-08-01",
    endDate: "2026-12-31",
    active: true,
    branchRestrictions: [],
    usageCount: 65,
    usageLimit: 500,
  },
  {
    id: "PROMO-003",
    code: "SAVE100K",
    title: "100,000 MMK Mega Saver Coupon (ငွေသား ၁ သိန်း တိုက်ရိုက် လျှော့စျေး)",
    type: "FIXED_AMOUNT",
    discountValue: 100000,
    minSpend: 1500000,
    startDate: "2026-08-15",
    endDate: "2026-09-30",
    active: true,
    branchRestrictions: [],
    usageCount: 19,
    usageLimit: 150,
  },
  {
    id: "PROMO-004",
    code: "VIPPLATINUM",
    title: "Platinum VIP Tier Auto-Perk (8% Off)",
    type: "TIER_DISCOUNT",
    discountValue: 8,
    minSpend: 0,
    startDate: "2026-01-01",
    endDate: "2026-12-31",
    active: true,
    branchRestrictions: [],
    targetTiers: ["PLATINUM"],
    usageCount: 156,
    usageLimit: 9999,
  },
  {
    id: "PROMO-005",
    code: "HAPPYHOUR50K",
    title: "Afternoon Happy Hour (50,000 Ks Off)",
    type: "HAPPY_HOUR",
    discountValue: 50000,
    minSpend: 1500000,
    startDate: "2026-08-01",
    endDate: "2026-08-31",
    active: true,
    branchRestrictions: ["BR-YGN-01", "BR-MDY-01"],
    usageCount: 28,
    usageLimit: 100,
  },
];

export const INITIAL_DYNAMIC_PRICING: DynamicPricingRule[] = [
  {
    id: "DPR-001",
    name: "Happy Hour Surge Discount (14:00 - 17:00)",
    targetCategory: "Audio & Accessories",
    ruleType: "TIME_WINDOW",
    adjustmentValue: -10, // -10% discount
    adjustmentType: "PERCENTAGE",
    startTime: "14:00",
    endTime: "17:00",
    active: true,
  },
  {
    id: "DPR-002",
    name: "Bulk Volume Tier (Buy 5+ units get 8% off)",
    targetCategory: "Audio & Accessories",
    ruleType: "VOLUME_TIER",
    adjustmentValue: -8,
    adjustmentType: "PERCENTAGE",
    minUnits: 5,
    active: true,
  },
  {
    id: "DPR-003",
    name: "Naypyidaw Outlet Logistics Regional Markup (+3%)",
    targetCategory: "Smart Home",
    ruleType: "REGIONAL_INDEX",
    adjustmentValue: 3,
    adjustmentType: "PERCENTAGE",
    branchId: "BR-NPT-01",
    active: true,
  },
  {
    id: "DPR-004",
    name: "Seasonal Campaign Promo (Aug 20 - Sep 15, Min 2 Qty → 12% Off)",
    targetCategory: "All Categories",
    ruleType: "DATE_RANGE",
    adjustmentValue: -12,
    adjustmentType: "PERCENTAGE",
    startDate: "2026-08-20",
    endDate: "2026-09-15",
    minUnits: 2,
    description: "Date-based promo across ALL Categories: buy 2 or more units between Aug 20 and Sep 15 to get 12% discount automatically.",
    active: true,
  },
  {
    id: "DPR-005",
    name: "Mega Spend Cashback Reward (Spend ≥ 500,000 Ks → 25,000 Ks Cash Back)",
    targetCategory: "All Categories",
    ruleType: "SPEND_CASHBACK",
    adjustmentValue: -25000,
    adjustmentType: "FIXED_AMOUNT",
    minSpend: 500000,
    cashbackAmount: 25000,
    description: "Instant cash discount of 25,000 MMK for orders exceeding 500,000 MMK threshold on all price categories.",
    active: true,
  },
];

export const INITIAL_EMPLOYEES: Employee[] = [
  {
    id: "EMP-001",
    employeeCode: "HQ-001",
    name: "U Kyaw Zayar",
    role: "HQ_ADMIN",
    branchId: "BR-YGN-01",
    branchName: "Yangon HQ Flagship",
    email: "kyaw.zayar@omnichain.com.mm",
    phone: "09790123456",
    baseSalary: 2800000,
    monthlyTargetSales: 120000000,
    salesAchieved: 110500000,
    status: "ACTIVE",
    clockedIn: true,
    clockInTime: "2026-08-21T08:15:00Z",
    totalShiftHoursToday: 6.5,
  },
  {
    id: "EMP-002",
    employeeCode: "MDY-001",
    name: "Daw Thandar Win",
    role: "BRANCH_MANAGER",
    branchId: "BR-MDY-01",
    branchName: "Mandalay Mega Tech Hub",
    email: "thandar.win@omnichain.com.mm",
    phone: "09790654321",
    baseSalary: 1800000,
    monthlyTargetSales: 80000000,
    salesAchieved: 78200000,
    status: "ACTIVE",
    clockedIn: true,
    clockInTime: "2026-08-21T08:45:00Z",
    totalShiftHoursToday: 6.0,
  },
  {
    id: "EMP-003",
    employeeCode: "YGN-CASH-01",
    name: "Aye Aye Myint",
    role: "CASHIER",
    branchId: "BR-YGN-01",
    branchName: "Yangon HQ Flagship",
    email: "ayeaye.myint@omnichain.com.mm",
    phone: "09443322110",
    baseSalary: 750000,
    monthlyTargetSales: 25000000,
    salesAchieved: 26800000,
    status: "ACTIVE",
    clockedIn: true,
    clockInTime: "2026-08-21T08:30:00Z",
    totalShiftHoursToday: 6.2,
  },
  {
    id: "EMP-004",
    employeeCode: "WH-LEAD-01",
    name: "Ko Min Thu",
    role: "WAREHOUSE_LEAD",
    branchId: "BR-WH-01",
    branchName: "Central Logistics Warehouse",
    email: "minthu.logistics@omnichain.com.mm",
    phone: "09790112233",
    baseSalary: 1200000,
    monthlyTargetSales: 0,
    salesAchieved: 0,
    status: "ACTIVE",
    clockedIn: true,
    clockInTime: "2026-08-21T07:45:00Z",
    totalShiftHoursToday: 7.0,
  },
  {
    id: "EMP-005",
    employeeCode: "ACC-001",
    name: "Daw Hla Hla Win",
    role: "ACCOUNTANT",
    branchId: "BR-YGN-01",
    branchName: "Yangon HQ Flagship",
    email: "hlahla.finance@omnichain.com.mm",
    phone: "09971100223",
    baseSalary: 1600000,
    monthlyTargetSales: 0,
    salesAchieved: 0,
    status: "ACTIVE",
    clockedIn: true,
    clockInTime: "2026-08-21T08:50:00Z",
    totalShiftHoursToday: 5.8,
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: "LOG-9921",
    timestamp: "2026-08-21T10:15:00Z",
    userId: "EMP-005",
    userName: "Htet Naing Oo",
    userRole: "CASHIER",
    branchName: "Mandalay Mega Tech Hub",
    action: "PROCESSED_SALE_INVOICE",
    category: "POS",
    ipAddress: "192.168.2.45",
    details: "Completed invoice INV-260821-002 for Daw May Thu Khaing via WavePay (MMK 1,246,875).",
    riskScore: "NORMAL",
  },
  {
    id: "LOG-9920",
    timestamp: "2026-08-21T09:45:00Z",
    userId: "EMP-003",
    userName: "Aye Aye Myint",
    userRole: "CASHIER",
    branchName: "Yangon HQ Flagship",
    action: "IMEI_SERIAL_SOLD",
    category: "POS",
    ipAddress: "192.168.1.12",
    details: "Sold iPhone 15 Pro Max with registered IMEI 358923114567890 (INV-260821-001).",
    riskScore: "NORMAL",
  },
  {
    id: "LOG-9919",
    timestamp: "2026-08-20T16:00:00Z",
    userId: "EMP-001",
    userName: "U Kyaw Zayar",
    userRole: "HQ_ADMIN",
    branchName: "Yangon HQ Flagship",
    action: "STOCK_SHRINKAGE_ADJUSTMENT",
    category: "INVENTORY",
    ipAddress: "192.168.1.10",
    details: "Approved stock write-down of 1 unit Anker 65W GaN (Damage in transit).",
    riskScore: "MEDIUM",
  },
  {
    id: "LOG-9918",
    timestamp: "2026-08-20T11:00:00Z",
    userId: "EMP-002",
    userName: "Daw Thandar Win",
    userRole: "BRANCH_MANAGER",
    branchName: "Mandalay Mega Tech Hub",
    action: "INTER_BRANCH_TRANSFER_REQUESTED",
    category: "INVENTORY",
    ipAddress: "192.168.2.1",
    details: "Dispatched transfer request TRF-2608-019 from Central WH to Mandalay.",
    riskScore: "NORMAL",
  },
  {
    id: "LOG-9917",
    timestamp: "2026-08-19T22:45:00Z",
    userId: "EMP-001",
    userName: "U Kyaw Zayar",
    userRole: "HQ_ADMIN",
    branchName: "Yangon HQ Flagship",
    action: "OFF_HOURS_CASH_DRAWER_OPEN",
    category: "SECURITY",
    ipAddress: "192.168.1.10",
    details: "Manual cash drawer audit recount at 22:45 PM after closing shift.",
    riskScore: "FLAGGED",
  },
];

export const INITIAL_USER_PROFILES: UserProfile[] = [
  {
    id: "USR-001",
    name: "U Kyaw Zayar",
    email: "kyaw.zayar@omnichain.com.mm",
    role: "HQ_ADMIN",
    branchId: "BR-YGN-01",
    branchName: "Yangon HQ Flagship",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    phone: "09790123456",
    mfaEnabled: true,
    permissions: ["*"],
  },
  {
    id: "USR-002",
    name: "Daw Thandar Win",
    email: "thandar.win@omnichain.com.mm",
    role: "BRANCH_MANAGER",
    branchId: "BR-MDY-01",
    branchName: "Mandalay Mega Tech Hub",
    avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80",
    phone: "09790654321",
    mfaEnabled: true,
    permissions: ["POS", "INVENTORY", "CRM", "REPORTS", "DISCOUNTS"],
  },
  {
    id: "USR-003",
    name: "Aye Aye Myint",
    email: "ayeaye.myint@omnichain.com.mm",
    role: "CASHIER",
    branchId: "BR-YGN-01",
    branchName: "Yangon HQ Flagship",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80",
    phone: "09443322110",
    mfaEnabled: false,
    permissions: ["POS_BILLING", "RETURNS", "RECEIPTS"],
  },
  {
    id: "USR-004",
    name: "Ko Min Thu",
    email: "minthu.logistics@omnichain.com.mm",
    role: "WAREHOUSE_LEAD",
    branchId: "BR-WH-01",
    branchName: "Central Logistics Warehouse",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    phone: "09790112233",
    mfaEnabled: true,
    permissions: ["GRN", "STOCK_TRANSFERS", "FLEET_DISPATCH", "WAREHOUSE_BINS"],
  },
];
